# Generated by Django 4.2.30 on 2026-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
